[workspace]
resolver = "2"
members = [
  "bitmaps",
#   "microbit-v1",
#   "microbit-v2",

]

# # Modify default build profiles to make debugging easier
# [profile.release]
# debug = 2
# lto = "off"

# [profile.dev]
# debug = 2
# opt-level = 1
# lto = "off"